### PR TITLE
move file completed logic

### PR DESCRIPTION
**Pull request by Shamwayne**

### CODE REVIEW

**Comment by smjohnsonShipyard** [comment]
Functionality looks fine so far. We may have missed this on the initial requirements. I would like the file to be named the same as the original file if moved and the user does not specify a new name with the destination_file_name argument. For example:
Original File: bp_test_from/picture.jpeg
Moved File: bp_test_to/picture.jpeg

**Comment by smjohnsonShipyard** [comment]
Error handling if the file doesn't exist and the bucket is wrong

**Comment by smjohnsonShipyard** [comment]
I'm getting a TypeError when trying to use regex to grab the files

image

**Comment by Shamwayne** [comment]
Should be good to retest, however had to try with my own credentials because was facing errors with the ones i was provided

**Pull request merged**
